import pandas as pd
from snomed_dict import SNOMED, SNOMEDHierarchy

if __name__ == "__main__":
    # Load SNOMED data
    snomed_path = "C:/Users/chris/OneDrive/Dokumenter/SDU/Master's Thesis Project/SNOMED/patoSnoMed_2025-04.xlsx"
    xls_snomed = pd.read_excel(snomed_path)
    df_snomed = pd.DataFrame(xls_snomed, columns=['SKSkode', 'DatoFra', 'DatoÆndring', 'DatoTil', 'Kodetekst', 'Fuldtekst'])
    snomed = SNOMED(df_snomed)
    
    # Focus on M-codes (morphology)
    m_codes = snomed.get_codes_by_letter('M')
    m_hierarchy = SNOMEDHierarchy(m_codes)

    # Get main regions
    # m_hierarchy.list_regions()

    # Look up each each main region
    m_hierarchy.list_subregions('M00')

    


# M00: ukendt morfologi (2 codes)
# M01: abnormt væv (2 codes)
# M02: abnorm form (2 codes)
# M03: pseudotumor (2 codes)
# M05: abnormt øget antal (2 codes)
# M09: for lidt materiale til diagnostisk vurdering (2 codes)
# M10: traumatisk læsion (2 codes)
# M11: forbrænding (2 codes)
# M12: fraktur (2 codes)
# M13: dislokation (2 codes)
# M14: kirurgisk incision (2 codes)
# M15: mangel, kirurgisk betinget (2 codes)
# M18: følge af kirurgisk indgreb (2 codes)
# M20: kongenit malformation (2 codes)
# M21: agenesi (aplasi) (2 codes)
# M22: kongenit septum (2 codes)
# M23: kongenit urogenital malformation (2 codes)
# M24: transposition (2 codes)
# M25: kongenit kutan malformation (2 codes)
# M26: ektopisk væv (2 codes)
# M27: kongenit malformation af uterus (2 codes)
# M28: graviditetsprodukt (2 codes)
# M29: abnorm placenta (2 codes)
# M30: calculus (2 codes)
# M31: displacering (2 codes)
# M32: dilatation (ektasi) (2 codes)
# M33: retention (2 codes)
# M34: okklusion (obstruktion) (2 codes)
# M35: blodkoagel (2 codes)
# M36: serom (2 codes)
# M37: blødning (2 codes)
# M38: ulcus (2 codes)
# M39: sekvester (2 codes)
# M40: inflammation (2 codes)
# M41: akut inflammation (2 codes)
# M42: subakut inflammation (2 codes)
# M43: kronisk inflammation (2 codes)
# M44: granulomatøs inflammation, granulom (2 codes)
# M45: inflammation med fibrose (2 codes)
# M46: inflammation med mekanisk misforhold (2 codes)
# M47: leukocytinfiltration (2 codes)
# M48: dermatitis (eksem) (2 codes)
# M49: fibrose (2 codes)
# M50: degenerativ forandring (2 codes)
# M51: katarakt (2 codes)
# M52: arteriosklerose (2 codes)
# M53: akut iskæmisk nefropati (2 codes)
# M54: nekrose (2 codes)
# M55: aflejring (2 codes)
# M56: dystrofi (2 codes)
# M57: pigmentering (2 codes)
# M58: atrofi (2 codes)
# M59: udgået se T59000 (2 codes)
# M61: abnorm karyotype (2 codes)
# M62: diploidi (2 codes)
# M63: trisomi 12 (2 codes)
# M65: pyknose (2 codes)
# M66: cytoplasmaforandring (2 codes)
# M67: ASCH - atypiske pladeepitelceller, muligt HSIL (2 codes)
# M68: basalmembranforandring (2 codes)
# M69: abnorme celler (2 codes)
# M70: abnorm endokondral ossifikation (2 codes)
# M71: hypertrofi (2 codes)
# M72: hyperplasi (2 codes)
# M73: metaplasi (2 codes)
# M74: dysplasi (kongenit) (2 codes)
# M75: modningsstop (2 codes)
# M76: proliferation (2 codes)
# M77: proliferation (hæmatopoietisk celle i blod) (2 codes)
# M78: abnormt perifert blod (2 codes)
# M79: graviditetshyperplasi (2 codes)
# M80: benign tumor (2 codes)
# M81: trikoepiteliom (2 codes)
# M82: cylindrom (ekkrint dermalt) (2 codes)
# M83: basofilt adenom (2 codes)
# M84: svedkirteladenom (2 codes)
# M85: intraduktalt karcinom, borderline (2 codes)
# M86: tekom (2 codes)
# M87: fæokromocytom (2 codes)
# M88: benign bløddelstumor (2 codes)
# M89: rhabdomyom (2 codes)
# M90: benign Brenner tumor (2 codes)
# M91: mola hydatidosa (2 codes)
# M92: osteoblastom (2 codes)
# M93: adenomatoid odontogen tumor (2 codes)
# M94: diffust astrocytom (2 codes)
# M95: neuroblastom (2 codes)
# M96: malignt lymfom i inkomplet remission (2 codes)
# M97: mycosis fungoides i inkomplet remission (2 codes)
# M98: udgået pr. 01.01.40, se M98008 (2 codes)
# M99: akut megakaryoblastleukæmi i inkomplet remission (2 codes)
# MAA: ny cytologisk prøve tilrådes (=ÆAA0X0) (2 codes)
# MYY: abnormt epitel (=M01050) (2 codes)
# MÆ0: se efterfølgende (2 codes)