
import re

# Manually defined dictionary mapping Danish anatomical location names to SNOMED code patterns (regex).
SNOMED_t_patterns = {
    "Topografi ukendt": r"T0000\d", 
    "Multiple lokalisationer": r"T000\d{2}",
    "Resektionsrand": r"T001\d{2}",
    "Hud, hår og negle": r"T0[123].*",
    "Cytologi, hud": r"T0Y200|T0Y5.*",
    "Mamma": r"T04.*",
    "Cytologi, mamma": r"T0Y4.*",
    "Hæmatopoietisk og retikuloendotelialt system": r"T0[56].*|T0X.*",
    "Milt" : r"T07.*",
    "Lymfeknuder og det lymfatiske system": r"T0[89].*",
    "Knoglesystem": r"T1[012].*|T1X5.*",
    "Skeletmuskulatur": r"T1[34].*",
    "Bursa, sener og ligamenter": r"T1[678].*",
    "Bløddelsvæv": r"T1X[02].*",
    "Glat muskulatur": r"T1X3.*",
    "Bruskvæv": r"T1X7.*",
    "Cytologi, synovialvæske": r"T1Y.*",
    "Næse og bihuler": r"T2[012].*",
    "Pharynx": r"T23.*|T60.*",
    "Larynx": r"T24.*",
    "Trachea": r"T25.*",
    "Bronkier og lunger": r"T2[6789].*",
    "Cytologi, luftveje": r"T2[XY].*",
    "Hjerte": r"T3.*",
    "Blodkar": r"T4.*",
    "Mundhule": r"T5[1234].*",
    "Spytkirtler": r"T55.*",
    "Lever": r"T56.*",
    "Galdeveje": r"T5[78].*",
    "Pancreas": r"T59.*|T99000",
    "Cytologi, fordøjelsessystem": r"T5[XY].*",
    "Tonsiller og adenoider": r"T61.*",
    "Esophagus": r"T62.*",
    "Ventrikel": r"T63.*",
    "Tarmsystem": r"T6[4-9].*|T50000|T50100|T50500|T6[X].*",
    "Fæces": r"T6Y.*",
    "Urogenitale system, NOS": r"T70000",
    "Nyrer": r"T7[12].*",
    "Ureter": r"T73.*",
    "Urinblære": r"T74.*",
    "Urethra": r"T75.*",
    "Penis": r"T76.*",
    "Prostata og vesicula seminalis": r"T77.*",
    "Testis og epididymis": r"T7[89].*",
    "Cytologi, urogenitale system": r"T7[XY].*",
    "Kvindelige kønsorganer": r"T8[01].*",
    "Uterus": r"T8[2,4-5].*",
    "Cervix uteri": r"T83.*",
    "Tuba uterina og ovarier": r"T8[67].*",
    "Placenta, fosterhinder og navlestreng": r"T88.*",
    "Foster og fostervand": r"T89.*",
    "Cytologi, kvindelige kønsorganer": r"T8[XY].*",
    "Endokrine system": r"T90.*",
    "Hypofyse": r"T91.*",
    "Epifyse": r"T92.*",
    "Binyre": r"T93.*",
    "Glomus caroticum": r"T94.*",
    "Paraganglie": r"T95.*",
    "Thyroidea": r"T96.*",
    "Parathyroidea": r"T97.*",
    "Thymus": r"T98.*",
    "Cilium": r"TE.*",
    "Rekonstruerede organer": r"TN.*",
    "Nervesystem": r"TX[0-9].*",
    "Øje": r"TXX.*",
    "Øre": r"TXY.*",
    "Hoved og hals": r"TY0.*",
    "Truncus (krop)": r"TY1.*",
    "Thorax": r"TY[23].*",
    "Abdomen": r"TY[45].*",
    "Pelvis, lysken": r"TY[67].*",
    "Overekstremitet": r"TY8.*",
    "Underekstremitet": r"TY9.*",
    "Øvrige": r"TY[XY].*|T00[1-9X].*",
}

# Function to categorize SNOMED codes based on the above patterns
def categorize_snomed(code):
    for category, pattern in SNOMED_t_patterns.items():
        if re.match(pattern, code):
            return category
    return "Udefineret"


# Max: Define complete code groups mapping from the document
code_groups = {
    "inflammation_group": {
        "name": "Inflammation and Fibrosis",
        "codes": {
            'M40000': 'Inflammation',
            'M41000': 'Acute inflammation',
            'M42100': 'Acute and chronic inflammation',
            'M43000': 'Chronic inflammation',
            'M44200': 'Non-necrotizing, granulomatous inflammation',
            'M45000': 'Inflammation with fibrosis',
            'M45020': 'Granulation tissue',
            'M48000': 'Dermatitis (eczema)',
            'M49000': 'Fibrosis',
        }
    },
    "neoplasia_group": {
        "name": "Neoplasia",
        "codes": {
            'M80013': 'Malignant tumor cells',
            'M80413': 'Small cell carcinoma - High-grade neuroendocrine tumor',
            'M80416': 'Metastasis, small cell neuroendocrine carcinoma',
            'M80520': 'Squamous papilloma',
            'M80703': 'Squamous cell carcinoma',
            'M80902': 'Superficial basal cell carcinoma',
            'M80903': 'Basal cell carcinoma',
            'M81203': 'Urothelial carcinoma',
            'M81302': 'Non-invasive papillary urothelial tumor',
            'M81403': 'Adenocarcinoma',
            'M81406': 'Metastasis, adenocarcinoma',
            'M87500': 'Dermal nevus',
            'M87600': 'Compound nevus',
            'M88320': 'Dermatofibroma (histiocytoma)',
            'M88500': 'Lipoma',
            'M88900': 'Leiomyoma',
            'M90841': 'Epidermoid cyst',
            'M91200': 'Hemangioma',
        }
    },
    "dysplasia_group": {
        "name": "Dysplasia and Cellular Abnormalities",
        "codes": {
            'M67010': 'ASCH - Atypical squamous cells, possible HSIL',
            'M67014': 'ASCUS - Atypical squamous cells of undetermined significance',
            'M67016': 'LSIL - Low-grade squamous intraepithelial lesion',
            'M67017': 'HSIL - High-grade squamous intraepithelial lesion',
            'M74AK9': 'CIN1 - Cervical intraepithelial neoplasia grade 1',
            'M74B09': 'Moderate dysplasia NOS',
            'M74BK9': 'CIN2 - Cervical intraepithelial neoplasia grade 2',
            'M74C09': 'Severe dysplasia NOS',
            'M807A2': 'CIN3 - Cervical intraepithelial neoplasia grade 3',
        }
    },
    "hyperplasia_group": {
        "name": "Hyperplasia and Non-Neoplastic Growth",
        "codes": {
            'M72000': 'Hyperplasia',
            'M72200': 'Nodular lymphatic hyperplasia',
            'M72600': 'Hyperkeratosis',
            'M72750': 'Seborrheic keratosis',
            'M72751': 'Irritated seborrheic keratosis',
            'M72850': 'Actinic keratosis',
            'M76701': 'Flat condyloma',
            'M76800': 'Polyp',
            'M76810': 'Fibroepithelial polyp',
        }
    },
    "normal_abnormal_group": {
        "name": "Normal/Abnormal Findings",
        "codes": {
            'M00010': 'Unknown morphology',
            'M00100': 'Normal morphology UNS',
            'M00120': 'Normal cells',
            'M00121': 'Normal cells, no endocervical or metaplastic cells',
            'M01111': 'Non-specific reactive change',
            'M09000': 'Insufficient material for diagnostic assessment',
            'M09010': 'Material unsuitable for diagnostics',
            'M09011': 'The material is less suitable for diagnostic assessment',
            'M09013': 'The material is not certainly representative',
            'M09014': 'The material is not representative',
            'M09015': 'Bloody material',
            'M09019': 'Material with too few endocervical cells',
            'M09400': 'Clear resection margins',
            'M09401': 'Resection margins not clear',
            'M09450': 'No evidence of malignancy',
            'M09462': 'No malignant suspect cells',
            'M09470': 'No evidence of metastasis',
        }
    },
    "hematologic_group": {
        "name": "Hematologic Conditions",
        "codes": {
            'M96003': 'Malignant lymphoma',
            'M97323': 'Myelomatosis',
            'M97651': 'Non-IgM monoclonal gammopathy of uncertain significance',
            'M98233': 'Chronic lymphocytic leukemia',
            'M99613': 'Myelofibrosis',
            'M99853': 'MDS with multilineage dysplasia',
            'M99893': 'Myelodysplastic syndrome',
        }
    },
    "procedures_group": {
        "name": "Procedural Codes",
        "codes": {
            'P30610': 'Biopsy',
            'P30611': 'Excision biopsy',
            'P30613': 'Punch biopsy',
            'P30615': 'Endoscopic biopsy',
            'P30619': 'Random biopsy',
            'P30620': 'Resection specimen',
            'P30625': 'Shaving resection specimen',
            'P30626': 'Curettage',
            'P30990': 'Needle biopsy',
            'P31060': 'Fine needle aspiration',
            'P31064': 'Fine needle aspiration, image-guided',
            'P31065': 'Fine needle aspiration, endoscopic',
            'P31066': 'Fine needle aspiration, EUS',
            'P31067': 'Fine needle aspiration, EBUS',
        }
    },
    "special_tests_group": {
        "name": "Special Tests and Findings",
        "codes": {
            'F10363': 'Increased iron content',
            'F10365': 'Lack of iron content',
            'FY5005': 'High risk HPV not detected',
            'FY5006': 'High risk HPV detected',
            'P31100': 'Cytological screening, biomedical analyst',
            'P31112': 'Cytological screening, automated',
            'P31113': 'Cytological screening, guided spot screening',
            'P33B35': 'Polymerase chain reaction, RNA analysis (RNA-PCR)',
        }
    },
    "other_conditions_group": {
        "name": "Other Pathological Conditions",
        "codes": {
            'M28000': 'Pregnancy-related tissue UNS',
            'M33400': 'Cyst',
            'M38000': 'Ulcer',
            'M54000': 'Necrosis',
            'M79310': 'Proliferation phase',
            'M79320': 'Secretion phase',
            'M79360': 'Inactive endometrium',
        }
    },
    "skin_location_group": {
        "name": "Skin Locations",
        "codes": {
            'T01000': 'Skin',
            'T02102': 'Skin on scalp',
            'T02104': 'Skin on forehead',
            'T02111': 'Skin on temple',
            'T02120': 'Skin on face',
            'T02121': 'Skin on cheek',
            'T02140': 'Skin on nose',
            'T02200': 'Skin on outer ear',
            'T02300': 'Skin on neck',
            'T02400': 'Skin on trunk',
            'T02410': 'Skin on shoulder',
            'T02420': 'Skin in axilla',
            'T02424': 'Skin on chest',
            'T02450': 'Skin on back',
            'T02480': 'Skin on abdomen',
            'T02511': 'Skin on vulva',
            'T02610': 'Skin on upper arm',
            'T02630': 'Skin on forearm',
            'T02810': 'Skin on thigh',
            'T02822': 'Skin on lower leg',
        }
    }
}

